//
//  AdImpression.swift
//  Hera
//
//  Created by Ali Ammar Hilal on 16.02.2022.
//

import Foundation

///  An ad impression is counted whenever an ad is displayed within an app.
///  Ad impressions vs clicks should not be confused with each other. In other words,
///  impressions in digital marketing tells advertisers and developers how many times
///  an ad was viewed by users. The ad impressions definition is not contingent how
///  many times the ad was clicked.
public struct AdImpression {
	
	/// The mediation source of the ad.
	public let provider: Provider
	
	/// The ad type i.e banner, rewarded, interstitial and native.
	public let adType: AdType
	
	/// The revenew generated by this ad.
	public let revenue: Double
	
	/// The ad source.
	public let network: String
	
	/// The type of bidding.
	public let biddingType: String?
}
